name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4

      - name: Cypress tests
        uses: ./
        with:
          working-directory: kitchen-sink/.github/workflow/main
          build: npm run build
          start: npm start
          config: baseUrl=https://example.cypress.io
          spec: |
            cypress/e2e/button.cy.js
            cypress/e2e/homepage.cy.js